### ISSUE TITLE
No ES6 support: Unexpected token name «of», expected punc «;»

### ISSUE THREAD

**Issue by sbrl** [circlecell/jscompress.com#11]
The following code snippet doesn't compress using [jscompress.com](http://jscompress.com/):

```javascript
function copyAttributes(src, dest, attrList)
{
	for(attrName of attrList)
	{
		dest.setAttribute(attrName, src.getAttribute(attrName));
	}
}

```

This make me think that jscompress.com doesn't support the `for..of` loop.

**Comment by vlucas** [comment]
JSCompress uses Uglify.js 2 for minification. I just checked over there, and it looks like ES6 support is being worked on in this issue: https://github.com/mishoo/UglifyJS2/issues/448

**Comment by sbrl** [comment]
Thanks for the link! I will follow that issue.

**Comment by finom** [comment]
Latest version of UglifyJS still doesn't support ECMAScript Next but I have added an option to use things from [harmony](https://github.com/mishoo/UglifyJS2/tree/harmony) branch.

**Comment by sbrl** [comment]
Cool, thanks!
