### ISSUE TITLE
Adds are overlapping page content

### ISSUE THREAD

**Issue by ericop** [circlecell/jscompress.com#20]
![image](https://cloud.githubusercontent.com/assets/5218249/14618440/9596c3fc-0580-11e6-9c64-e0ea47b99531.png)

The **rackspace** ad is over-extending it's container on the bottom, and more importantly so is the **appdynamics** but it's covering up your
> JSCompress.com is an online javascript compressor...

paragraph. Might want to look into that.

**Comment by finom** [comment]
Thanks
