### ISSUE TITLE
Suggestion: when clicking on output tab

### ISSUE THREAD

**Issue by lordspace** [circlecell/jscompress.com#27]
It would be nice to auto select the minified content when the user clicks on the text area in the output tab. It's just one line of js.

if you have time it also be nice to have a Copy button near the download button.
This button would copy the minified version to the clipboard (zero clipboard?)
When you have the 2 buttons you may want to color one of them differently as primary one.

P.S. Great service :) I use it all the time.

P.S 2: I am wondering if there would be a business idea if you create an api that people can call curl and it returns raw minified version

You could inject a comment in the compressed file e.g. 
/\* compressed/minified by jscmpr.com */
jscmpr.com is available and can redirect to the main domain.

Take care,
Slavi

**Comment by finom** [comment]
Nice idea about the copy button, thanks.

About the API, we likely are not going to do this. If you can use CLI you can also use UglifyJS2 or babel-minify.

**Comment by finom** [comment]
After going to Output tab the content is selected and you can just press Ctrl+C to copy the result to the clipboard. I'd  not like to add another button to keep the tool minimalistic. Thank you.
