### ISSUE TITLE
Unicode letters convert to unrecognized characters on ECMAScript2017

### ISSUE THREAD

**Issue by Azekthi** [circlecell/jscompress.com#32]
`var asciiLetters = ["🇦", "🇧", "🇨", "🇩", "🇪", "🇫", "🇬", "🇭", "🇮", "🇯", "🇰", "🇱", "🇲", "🇳", "🇴", "🇵", "🇶", "🇷", "🇸", "🇹", "🇺", "🇻", "🇼", "🇽", "🇾", "🇿"];`

Minifying this results in:

`var asciiLetters=["�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�","�"];`

EDIT: 🔵 also converts to �.

**Comment by Azekthi** [comment]
This has still not been fixed with the new ECMAScript2017. The same exact issues in the first post are present.

**Comment by finom** [comment]
This is UglifyJS issue https://github.com/mishoo/UglifyJS2/issues/1820
Waiting for fix/response from their side.

**Comment by finom** [comment]
Now we use Babili for ES Next mode instead of UgisyJS. @Azekthi thank you.
