### ISSUE TITLE
Issue when i compressed file angular 2 js on safari

### ISSUE THREAD

**Issue by khoapossible** [circlecell/jscompress.com#33]
I got issue when i compressed file js which is builded by angular 2 (newest version, angular 4.0), this issue happen on safari.
It will work, when i replace "let a" to "var a", "let b" to "var b" ..etc.
Thank for your reading.
![screen shot 2017-04-07 at 3 00 49 pm](https://cloud.githubusercontent.com/assets/17254044/24791220/8a8e97d4-1ba3-11e7-989e-3d518426b3a3.png)

**Comment by finom** [comment]
@khoapossible please provide a code (localize first) which isn't compiled at jscompress.com.

**Comment by finom** [comment]
Closing because of no response.
