### ISSUE TITLE
Top-level vars no longer being shortened

### ISSUE THREAD

**Issue by campbeln** [circlecell/jscompress.com#34]
In previous versions of JSCompress, top level `var`s would get shortened, so I took to doing some code-golf declarations at the top to squeeze out a few more bytes. However, these do not seem to be working as they used to. For example, here is the top of a large codebase I maintain:

`!function(){"use strict";var _window=window,_document=document,_head=_document.head,_undefined,_null=null,_true=!0,_false=!1,_document_currentScript=_document.currentScript,_Object_prototype_toString=Object.prototype.toString,_document_querySelector=_document.querySelector.bind(_document),_document_querySelectorAll=_document.querySelectorAll.bind(_document),_Date_now=Date.now,oCoreOptions={},fnExpectedErrorHandler=function(){},oInterfaces={pub:function(){return{data:{},options:{},ui:{}}}},core=function(e,r){return r?core.mk.arr(_document_querySelectorAll(e)):_document_querySelector(e)};core.ver="0.9.2018-01-12",core.app=oInterfaces.pub(),core.lib=oInterfaces.pub(),core.resolve=function(){var e,r,t,n,o,c,i,a,s={allowFn:_true}...`

As can be seen above, the first `var` list is being left as-is, while those in the function at the end of the sample above are shortened to `var e,r,t,n,o,c,i,a,s={allowFn:_true}...`. I can see the list is still being processed because `_true=!0,_false=!1` are present. However, even the non-code-golf-y variables are being left unshortened, like `fnExpectedErrorHandler=function(){}`!?

Is this an intentional change? Should I give up on my code-golf byte squeezing or is this a bug to be fixed?

**Comment by finom** [comment]
@campbeln sorry for long response. Do you use "ECMAScript 2018" mode? Can you please provide me a valid piece of code so I can reproduce the issue by myself?

**Comment by campbeln** [comment]
Apologies myself for the slow turnaround!

This codebase is the one I've been having issue with, though with my latest test it seems to be working on top-level variables again - https://github.com/campbeln/core/blob/master/core.split.js

Even the old codebase that was definitely having issues is also encoding correctly - https://github.com/campbeln/core/blob/master/core.js

So... I guess it's been fixed!

Also, I was not using "ECMAScript 2018".
