### ISSUE TITLE
TypeError: unknown: Cannot read property 'referencePaths' of undefined

### ISSUE THREAD

**Issue by LapysDev** [circlecell/jscompress.com#35]
The file to be compressed is quite large (**1.52 MB**) but I keep getting this error message (**TypeError: unknown: Cannot read property 'referencePaths' of undefined**) when I try to compress it on the website [https://jscompress.com](https://jscompress.com/).

I've already searched the file thoroughly and there's nothing matching the search: _referencePaths_ (or _paths_, or _reference_ (and yes, I searched regardless of casing)).

Any reason why this happens?

![132](https://user-images.githubusercontent.com/22405610/42552833-2b6eaf8a-84d6-11e8-96f4-c3dce15a6282.png)

Thanks for any responses to solve this problem.

**Comment by finom** [comment]
@LapysDev can you drop the file please so I can reproduce the bug?

**Comment by finom** [comment]
@LapysDev I cannot reproduce the bug and there was no response from you. I'm closing the issue. Also babel-minify has been upgraded and this bug may be already fixed.
