### ISSUE TITLE
Lost js cause unknow error

### ISSUE THREAD

**Issue by natilux2** [circlecell/jscompress.com#37]
I'm currently using your jscompress and feel so good
Today, my js code could not be compressed as usual ( I adready try both paste code and upload file)
Here my js code, can you reprocedure it and fix it 

$(document).ready(function() {
    $(".export-time").daterangepicker({timePicker:!1,format:"DD-MM-YYYY",separator:" -> "},function(t,e,o){$(".export-time").val(t.format("DD-MM-YYYY")+" -> "+e.format("DD-MM-YYYY"))}),$(".export-time-i").click(function(){$(this).hasClass("cur-pointer")&&$(this).closest("div").find("input").focus()}),$("#modal-detail-product, #modal-detail-contract-pay, #modal-ProductOtherNewsUpdate-info").modal("hide"),sessionStorage.setItem("ValidSession",parseInt('@Session["Verify"]')),sessionStorage.setItem("PCAL",parseInt("@Model.Pcal")),"dashboard"==sessionStorage.getItem("link")&&($(".btn-primary-go-back").text("Đóng"),$(".btn-primary-go-back").attr("data-dismiss","modal").removeClass("btn-primary-go-back")),"report"==sessionStorage.getItem("link")&&($(".btn-primary-go-back, .show-export-contract,.show-export-pack, #btnUpdateContract, #btnUpdateLiteContract").remove(),sessionStorage.removeItem("link"));
    if ('@Model.ContractId' > 0) {
        sessionStorage.setItem('CONTRACT_VAT', '@Model.VAT');
        sessionStorage.setItem('CONTRACT', '@Model.ContractId');
        if(2==parseInt('@Session["Verify"]')){var verify=parseInt($("#ContractInfo").attr("verify"));2==verify?($("#ContractInfo").find(".panel-body").addClass("bg-danger"),$("#ContractInfo").find(".panel-body").css({border:"1px solid #bd0000"})):1==verify&&$.ajax({type:"POST",contentType:"application/json",url:'@Url.Action("SetContractColorChange", "ManagerContract")',data:"{ContractId:@Model.ContractId}",success:function(a){for(var t=a.split(","),e=0;e<t.length;e++)switch(t[e]){case"ClientId":$("#txtClientId").closest("div").addClass("has-error"),$("#txtClientId").addClass("bg-danger");break;case"ContractDate":$("#txtContractDate, #txtContractDateLite").closest("div").addClass("has-error"),$("#txtContractDate, #txtContractDateLite").addClass("bg-danger");break;case"ExpireDate":$("#txtExprireDate, #txtExprireDateLite").closest("div").addClass("has-error"),$("#txtExprireDate, #txtExprireDateLite").addClass("bg-danger");break;case"ContractStatus":$("#cboContractStatus").closest("div").addClass("has-error"),$("#cboContractStatus").addClass("bg-danger");break;case"SalerId":$("#txtSalerId").closest("div").addClass("has-error"),$("#txtSalerId").addClass("bg-danger");break;case"VAT":$("#txtVAT").closest("div").addClass("has-error"),$("#txtVAT").addClass("bg-danger");break;case"ContactClientId":$("#cboContactClient").closest("div").addClass("has-error"),$("#cboContactClient").addClass("bg-danger");break;case"PayDate":$("#txtPayExpireDate").closest("div").addClass("has-error"),$("#txtPayExpireDate").addClass("bg-danger");break;case"MaVungMien":$("#cboRegionSelector").closest("div").addClass("has-error"),$("#cboRegionSelector").addClass("bg-danger");break;case"Amount":$("#txtTotal, #txtTotalLite").closest("div").addClass("has-error"),$("#txtTotal, #txtTotalLite").addClass("bg-danger");break;case"SalerBookingId":$(".saler-booking-div").addClass("has-error")}}}),$("#btnExpand").trigger("click")}
        $.ajax({type:"POST",contentType:"application/json",url:'@Url.Action("ViewDetailContractPayList", "ManagerContract")',data:"{ContractId:@Model.ContractId}",success:function(t){$(".content-pay-list").empty().append(t),2==parseInt('@Session["Verify"]')&&$(".content-pay-list").find("tbody > tr").each(function(){var t=$(this).attr("id");if(void 0!==t){var n=$(this),a=n.attr("verify");n.addClass("show-change-contract-pay cur-pointer"),2==parseInt(a)?(n.addClass("bg-danger"),n.find("td").css({color:"#843534"})):1==parseInt(a)&&$.ajax({type:"POST",contentType:"application/json",url:'@Url.Action("SetContractPayColorChange", "ManagerContract")',data:"{ContractPayId:"+t+"}",success:function(t){for(var a=t.split(","),e=0;e<a.length;e++)switch(a[e]){case"PlanDate":n.find(".td-plandate").addClass("text-red");break;case"ExpireDate":n.find(".td-expiredate").addClass("text-red");break;case"Amount":n.find(".set-total-amount").addClass("text-red");break;case"Note":n.find(".set-description").addClass("text-red")}}})}})}});
        $('#ajax_loading').removeAttr('style');
        $.ajax({type:"POST",contentType:"application/json",url:'@Url.Action("LoadContentProduct", "ManagerContract")',data:"{ContractId:@Model.ContractId}",success:function(t){$(".content-product-list").empty().append(t),DesAndPrice(),bindClick(parseInt('@Session["Verify"]'),parseInt('@HttpContext.Current.Session["CheckQuantityChild"]')),$("#ajax_loading").css("display","none"),2==parseInt('@Session["Verify"]')&&$(".content-product-list").find("tbody > tr").each(function(){var d=$(this).attr("id");if(void 0!==d){var t=$(this).attr("verify"),n=$(this),e=n.attr("class");2==parseInt(t)&&1==parseInt(n.data("news-parent"))||2==parseInt(t)&&-1==e.indexOf("nd-new")||-1==parseInt(t)&&-1<e.indexOf("nd-new")||2==parseInt(t)&&-1<$(this).find(".inline-edit-product").find("span:first").text().toLowerCase().indexOf("mới")?(n.removeAttr("style"),n.removeClass("bg-warning").addClass("bg-danger"),n.find("td").css({color:"#843534"})):1==parseInt(t)&&$.ajax({type:"POST",contentType:"application/json",url:'@Url.Action("SetProductColorChange", "ManagerContract")',data:"{ProductId:"+d.split("-")[0]+"}",success:function(t){for(var e=t.split(","),a=0;a<e.length;a++)switch(e[a]){case"FromDate":n.find("td:eq(3)").find("div:eq(0)").find("span").addClass("text-red");break;case"ToDate":n.find("td:eq(3)").find("div:eq(1)").find("span").addClass("text-red");break;case"SL":n.find("td:eq(4)").addClass("text-red");break;case"Price":n.find("td:eq(5)").addClass("text-red");break;case"Amount":n.find("td:eq(7)").addClass("text-red");break;case"Discount":n.find("td:eq(6)").addClass("text-red");break;case"AmountDetail":$(".amount-detail-"+d).find("td:eq(5)").addClass("text-red"),$(".amount-detail-"+d).find("td:eq(7)").addClass("text-red");break;case"AmountOther":$(".amount-other-"+d).find("td:eq(5)").addClass("text-red"),$(".amount-other-"+d).find("td:eq(7)").addClass("text-red");case"Label":n.find(".mark-label").addClass("text-red")}}})}}),0<parseInt("@Model.iDisplay")&&ResizeLbContract()}});
    }
    LoadTokenUserBoostrap()
});

**Comment by finom** [comment]
@natilux2 it's fixed now but a part of your code is going to be erased anyway because it's unreachable: `if ('@Model.ContractId' > 0) {`.
