### ISSUE TITLE
Bug: let and const keywords unhandled

### ISSUE THREAD

**Issue by System-Glitch** [circlecell/jscompress.com#38]
## Description

**Environment:** production ( https://jscompress.com/ )  
**Reproduces:** always  

It looks like `let` and `const` keywords are not handled and prevent the file from being minified.

### How to reproduce

**Input:**
```
let foo = 'bar';
```

**Output:**
```
Unexpected token: name (foo) (line: 1, col: 4)
```

**Expected result:**  
```
let foo="bar";
```

## Additional information

The issue occurs in both copy-paste and file upload modes.

**Comment by finom** [comment]
@System-Glitch we use UglifyJS for the tool which doesn't support the new JS syntax (at least before we update it) but you also can enable Babili (which is not called babel-minify) for compression via checkbox at top right corner.

![image](https://user-images.githubusercontent.com/1082083/52406391-43c71800-2ad6-11e9-8cec-50e9efa6204c.png)
