### ISSUE TITLE
Feature request: Download compressed.js directly

### ISSUE THREAD

**Issue by laukstein** [circlecell/jscompress.com#39]
Currently click on Download will download jscompress-result.zip containing compressed.js .
I propose to download it directly as compressed.js, know that you can simply use HTML5 element attribute `download="compressed.js"` for it, examples in https://www.w3schools.com/tags/att_a_download.asp

Spec details https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes

**Comment by laukstein** [comment]
@finom did the fix already landed? It still keeps downloading zip file after compressed pasted single JS file code.

**Comment by finom** [comment]
@laukstein not yet, I'm getting deployment issues. The new version is going to be landed soon.

**Comment by finom** [comment]
Everything is good now.
