### ISSUE TITLE
Minified scripts break since today

### ISSUE THREAD

**Issue by WolfeyT** [circlecell/jscompress.com#41]
Sorry I am not very familiar with github and git overall, I just use your JS compressor pretty often. I last used it yesterday or the day before that and everything was fine, but since today my script stops working after being minified. It works before minified and the minified version I backed up yesterday works too. Have you changed anything?
Sorry I'm not being specific, I just can't find what exactly breaks, since the script is minified and not readable anymore.
The site itself works, but is like super super slow, it must take at least 30 seconds to minify a script and browser just hangs/becomes not responsive in this time. Last week compressing took around 10-15 seconds and the browser wasn't hanging like that.

**Comment by WolfeyT** [comment]
I now see, you dropped UglifyJS and now only use babel. That's why my scripts seem to break. I tried to download older version before the commit and running it on my server, but it sais /js/app.js is missing, why is that? Is this file not included?

**Comment by finom** [comment]
@WolfeyT sorry for the issues. The reason of them is that we've removed uglyfyjs and used babel-minify by default. Since a lot of people facing various problems I'm going to bring uglifyjs back.

**Comment by WolfeyT** [comment]
Thank you for your assistance Andrey.
I think it's always a good thing to give people a choice. Maybe if you want to move to babel you could make it the new default, but still leave the option for people facing issues to use the old uglify version instead. I mean it works and it's not like there are security issues, so why not let it be.

**Comment by finom** [comment]
@WolfeyT brought back the same but updated set up.
