### ISSUE TITLE
Doesn't support arrow functions

### ISSUE THREAD

**Issue by cyruscook** [circlecell/jscompress.com#43]
Attempting to compress code using arrow functions gives the following error:
```
Unexpected token: punc ()) (line: 1, col: 9)
```

The code I am attempting to compress is this:
```javascript
var e = () => {
	document.body.classList.add("no-scroll");
}
```

Please could you add support for arrow functions? I am going to have to use another compressor in the meantime.

**Comment by reidsvilleneuve** [comment]
That snippet should work if you enable the "ECMAScript 2019 (via babel-minify)" checkbox near the upper-right of the main field as seen here:

<img width="818" alt="checkbox" src="https://user-images.githubusercontent.com/8031639/56623943-bfbfff00-65f3-11e9-8d89-957b7b399988.png">
