### ISSUE TITLE
Prototype extensions to built-in primitives are lost

### ISSUE THREAD

**Issue by ebird2211** [circlecell/jscompress.com#45]
When extending built-in primitives, such as String, the prototype extension is lost.

Example:
```
   String.prototype.trimsplit = function(delimiter) {
      return this.match(/^\s*(.*[^\s])\s*$/)[1]
                 .split(new RegExp('\\s*' + delimiter + '\\s*'));
   }
```
This code gets completely omitted from the compressed output.

However, when putting this code in an anonymous function, it gets correctly compressed and included:
```
   (function() {
      String.prototype.trimsplit = function(delimiter) {
         return this.match(/^\s*(.*[^\s])\s*$/)[1]
                    .split(new RegExp('\\s*' + delimiter + '\\s*'));
      }
   })()
```

**Comment by finom** [comment]
Hmm, cannot reproduce. Maybe it was fixed after last dependencies upgrade?
