### ISSUE TITLE
Special chars encoding (non-ASCII)

### ISSUE THREAD

**Issue by SufyanJabr** [circlecell/jscompress.com#49]
I notice an issue with (non-ASCII) chars. 

e.g. 
function x()
{
return /\w/.test(ch) || ch > "\x80";
}

will compress to:
function x(){return/\w/.test(ch)||""<ch}

**Comment by CarlosERodriguez** [comment]
Hi, i have the same issue.

**Comment by BackuPs** [comment]
![afbeelding](https://user-images.githubusercontent.com/6078370/67031276-6dc6e480-f111-11e9-8619-7a94f1ebe4d1.png)

**Comment by finom** [comment]
Right, please use babel-minify option.
