### ISSUE TITLE
Error compressing on jscompress.com - TypeError: unknown: setting getter-only property "inList"

### ISSUE THREAD

**Issue by denlem** [circlecell/jscompress.com#50]
This code is compressing successfully
```
var opacity_hide = 1;
for (var i = 1; i <= 10; i++){
    var opacity_hide = (10-i)/10;
    // var delaytest = 1;
}
```

But this code is not compressing , and prints error:

```
var opacity_hide = 1;
for (var i = 1; i <= 10; i++){
    var opacity_hide = (10-i)/10;
    var delaytest = 1;
}
```
Error:
File maintest.js: TypeError: unknown: setting getter-only property "inList"

It cause only if "ECMAScript 2019 (via babel-minify)" is checked

**Comment by vincentstack** [comment]
Having the same issue... this does not compress correctly with ECMAScript 2019 (via babel-minify)"  checked

function getNewsItemByNewsItemID(newsitemid) {
    if (!newsitemid) {
        return;
    }
    var uri = '/NewsItemsAPI/GetNewsItemByNewsItemID?newsitemid=' + newsitemid;
    $("#myLoadPanel").dxLoadPanel("instance").option("visible", true);
    fetch(uri)
        .then(function (response) {
            console.log(response);
            return response.json();
        })
        .then(function (data) {
            updateUIGetNewsItemByNewsItemID(data);
            

        })
        .catch(function (err) {
            updateUIGetNewsItemByNewsItemIDError();
            console.log(err);
        });
}

**Comment by Anorionil** [comment]
We're also having the same issue.
