### ISSUE TITLE
Does not recognize const keyword

### ISSUE THREAD

**Issue by HydronicDev** [circlecell/jscompress.com#55]
Having a const variable is not known by the minifier.

**Comment by finom** [comment]
Please use the babel option to compile non ES5 code.
![image](https://user-images.githubusercontent.com/1082083/84534174-202b6780-acf2-11ea-88a1-5f0adca89044.png)

**Comment by jxmot** [comment]
As of today the site is still producing this error:

`Unexpected token: keyword «const» `

**Comment by BackuPs** [comment]
> 
> 
> As of today the site is still producing this error:
> 
> `Unexpected token: keyword «const» `

I swapped to a better one without issues as this one is still not a complete download package which i have reported serveral times now. It does not run standalone as js files are missing and every time the developer asks me which ones, I answer and he never gets back after that. So i gave up ! You better use this one

https://javascript-compressor.com/
