### ISSUE TITLE
app.js in the js folder is still missing

### ISSUE THREAD

**Issue by BackuPs** [circlecell/jscompress.com#56]
Hi

the app.js file in the js.folder is still missing in the download package. How to get that?

also the babel transfrom js files are missing

vendors~babelTransform-chunk-24844acb4277512e70fd.js
babelTransform-chunk-fe622da15389dffa17f3.js

please advice

Do i have to build these files myself?  If so how ?  Please advice.

Thank you

**Comment by finom** [comment]
@BackuPs sorry, can you describe in details what did you do and what you've tried to achieve. I've checked out the app and everything worked for me.

**Comment by BackuPs** [comment]
@finom 

Sorry if i am not clear.

if i download the master build zip file from github. And upload it in my server or even use it locally on my pc It does not work as 3 js files are not part of the master build. They are missing.

The following files are missing as they are not included in the master build. 

app.js
vendors~babelTransform-chunk-24844acb4277512e70fd.js
babelTransform-chunk-fe622da15389dffa17f3.js

So the compress does not work at all once you click the compress button.  Without emascript enabled you the message that app.js is not found. If you enable emascript then you get the js error that the babel js files are missing.

The master zip file is in my opinion incomplete. I reported this also allmost more then a year ago and the files are still not included.

Or please tell me how to generate or get these files.

Kind regards,

**Comment by BackuPs** [comment]
are we gonna get a solution for this?

**Comment by minig0d** [comment]
> @finom
> 
> Sorry if i am not clear.
> 
> if i download the master build zip file from github. And upload it in my server or even use it locally on my pc It does not work as 3 js files are not part of the master build. They are missing.
> 
> The following files are missing as they are not included in the master build.
> 
> app.js
> vendors~babelTransform-chunk-24844acb4277512e70fd.js
> babelTransform-chunk-fe622da15389dffa17f3.js
> 
> So the compress does not work at all once you click the compress button. Without emascript enabled you the message that app.js is not found. If you enable emascript then you get the js error that the babel js files are missing.
> 
> The master zip file is in my opinion incomplete. I reported this also allmost more then a year ago and the files are still not included.
> 
> Or please tell me how to generate or get these files.
> 
> Kind regards,

Can you just download them from the jscompress.com site?

https://jscompress.com/js/app.js
https://jscompress.com/babelTransform-chunk-db67fff9d94e29aa2a74.js
https://jscompress.com/vendors~babelTransform-chunk-38b72474cce8bd4fb904.js

**Comment by BackuPs** [comment]
@minig0d thank you for the suggestion but i already knew how to grab them, but that is not the point i am trying to make. 

The issue is they change every now an then after each update and the point i am trying to make here is that the zip file is incomplete whereas the owner of jscompress says "and works 100% on client-side."  Which is not true. 

The moment you unzip the build and f.e. run it on your localmachine these files are missing and you get a js error.

I did report this several times now with no result to a solution so I decided to switch to another online js compressor a long time ago! Sorry about that.

**Comment by finom** [comment]
@BackuPs sorry, the reason of my long response was the fact that I haven't understood what you're trying to do. I guess you wanted to clone the repository and run the app locally? If the discussion still makes sense to you and my suggestion is correct, you should run build NPM script to get all the needed files.

**Comment by BackuPs** [comment]
@finom Thanks.  I was under the impression that the zip file contained all the required files needed to make it run locally on my pc or server.  I was not aware that i needed to run the npm script.

Thanks

**Comment by BackuPs** [comment]
so in order to get a full working package i have to install nodjs, npm, uglify.js etc etc...  

I just wanted a 100% working product without having todo all these extra things on my machine. Now i need to dive into a lot of extra things to get to the end product. :-(
